# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: goxmpp
      POSTGRES_PASSWORD: aaZ82w282EwNch5

    ports:
      - 5432:5432
